name: boundary-dev-mode-test 

on: [push]

jobs:
  boundary-dev-mode-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download, unzip and start Boundary in dev mode
      run: |
        wget https://releases.hashicorp.com/boundary/0.1.0/boundary_0.1.0_linux_amd64.zip
        unzip boundary_0.1.0_linux_amd64.zip
        bash -c "boundary dev" &
        sleep 30
    - name: Run cargo example to test auth works
      run: |
        cargo run --example auth-dev-mode | grep 'status: 200'
        echo $?
